### PR TITLE
albs-sign-node: install glibc-langpack-en

### PR DESCRIPTION
**Pull request by metalefty**
Resolves: https://github.com/AlmaLinux/build-system/issues/196

### CODE REVIEW

**Comment by metalefty** [comment]
@javihernandez Commit Message Check is not checking the latest commit, any ideas? I force-pushed 0ec8965 and it is the latest commit.

- https://github.com/AlmaLinux/albs-sign-node/commit/69b081010c275d25b2ee27a53b70b8233b1d9339.patch
- https://github.com/AlmaLinux/albs-sign-node/commit/0ec89655128c5c2b6ee404f3452163dbde2c418d.patch

**Comment by javihernandez** [comment]
> @javihernandez Commit Message Check is not checking the latest commit, any ideas? I force-pushed [0ec8965](https://github.com/AlmaLinux/albs-sign-node/commit/0ec89655128c5c2b6ee404f3452163dbde2c418d) and it is the latest commit.

There's a TAB between `Resolves:` and link - it should be a blank space

**Comment by metalefty** [comment]
No no, I didn't mean that.

**Comment by metalefty** [comment]
Ah,  sorry. The CI task name confused me. I had assumed it complains about commit message because the task is named "Commit Message Check". It is not a very good name :(

image

**Comment by metalefty** [comment]
What I tried to fix in the pull request is to ensure `glibc-langpack-en` installed before using `en_US.UTF-8` because `glibc-langpack-en` contains locales for `en_*`. 

```
$ rpm -ql glibc-langpack-en
/usr/lib/locale
/usr/lib/locale/en_AG
/usr/lib/locale/en_AG/LC_ADDRESS
/usr/lib/locale/en_AG/LC_COLLATE
/usr/lib/locale/en_AG/LC_CTYPE
/usr/lib/locale/en_AG/LC_IDENTIFICATION
...
/usr/lib/locale/en_ZW/LC_PAPER
/usr/lib/locale/en_ZW/LC_TELEPHONE
/usr/lib/locale/en_ZW/LC_TIME
/usr/share/locale/en_GB/LC_MESSAGES/libc.mo
```

The easiest code to reproduce kind of error in the original issue https://github.com/AlmaLinux/build-system/issues/196 is just a 2-line python code.

```python
#!/usr/bin/python

import locale
locale.setlocale(locale.LC_ALL, "en_US.UTF-8")
```

### glibc-langpack-en is not installed
```
$ rpm -qa | grep glibc-langpack-en
$

$ python localecheck.py
Traceback (most recent call last):
  File "/tmp/localecheck.py", line 5, in <module>
    locale.setlocale(locale.LC_ALL, "en_US.UTF-8")
  File "/usr/lib64/python3.9/locale.py", line 610, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

### glibc-langpack-en is installed
```
$ sudo dnf install -y glibc-langpack-en
$

$ python localecheck.py
$
```

Success without error.

**Review by maccelf — APPROVED** [review]

**Review by zklevsha — APPROVED** [review]

**Pull request merged**
